/**
 * The StreamForest mark: a play triangle whose trailing edge is cut into fir
 * branches.
 *
 * One component rather than an inline <svg> per site, because the mark also ships
 * as four PNGs and a favicon generated by tools/build-icons.mjs — five copies of
 * the same path is how a logo drifts. The path here and the one there are the
 * same string; change both together.
 *
 * Gradient ids are suffixed per instance: SVG gradients share a document-wide
 * namespace, and the sidebar and the install prompt can be on screen at once.
 */
let seq = 0

export function Logo({ size = 28, className = '' }: { size?: number; className?: string }) {
  const id = `sf-logo-${(seq += 1)}`
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 512 512"
      fill="none"
      className={className}
      role="img"
      aria-label="StreamForest"
    >
      <defs>
        <linearGradient id={`${id}-bg`} x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stopColor="#0d4a35" />
          <stop offset="1" stopColor="#02150f" />
        </linearGradient>
        <linearGradient id={`${id}-mark`} x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stopColor="#6ee7b7" />
          <stop offset="1" stopColor="#10b981" />
        </linearGradient>
      </defs>
      <rect width="512" height="512" rx="120" fill={`url(#${id}-bg)`} />
      <path
        d="M176 112 L392 256 L176 400 L176 344 L248 344 L176 296 L176 240 L248 240 L176 192 Z"
        fill={`url(#${id}-mark)`}
      />
    </svg>
  )
}
