app = "streamforest-transcode"
primary_region = "arn"

[build]

[env]
  PORT = "8787"
  ALLOWED_HOSTS = "iptvworld.xyz"

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
